version: 2.1

jobs:
  say_hello:
    machine: true  # Use a self-hosted runner machine
    resource_class: gitactionorg/circleci  # Replace with your self-hosted runner's resource class
    steps:
      - run: echo "Say hello to YAML onkar!"

  say_goodbye:
    machine: true  # Use a self-hosted runner machine
    resource_class: gitactionorg/circleci  # Replace with your self-hosted runner's resource class
    steps:
      - run: echo "Say goodbye to YAML new!"

  build_and_test_maven:
    machine: true  # Use a self-hosted runner machine
    resource_class: gitactionorg/circleci  # Replace with your self-hosted runner's resource class
    steps:
      - checkout  

      # Run Maven build and tests
      - run: mvn clean install

      # Generate JaCoCo coverage report
      - run: mvn jacoco:report

      # Generate test results in JUnit format (for CircleCI to parse)
      - run: mvn surefire-report:report

      # Store code coverage report as artifacts
      - store_artifacts:
          path: target/site/jacoco/index.html
          destination: code-coverage

      # Store test results (JUnit XML)
      - store_test_results:
          path: target/surefire-reports

workflows:
  hello_and_goodbye:
    jobs:
      - say_hello
      - say_goodbye
      - build_and_test_maven
