version: 2.1

jobs:
  say_hello:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to YAML onkar!"
  
  say_goodbye:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say goodbye to YAML new!"
  
  build_and_test_maven:
    docker:
      - image: cimg/openjdk:17.0  
    steps:
      - checkout  

      # Run Maven build and tests
      - run: mvn clean install

      # Generate JaCoCo coverage report
      - run: mvn jacoco:report

      # Generate test results in JUnit format (for CircleCI to parse)
      - run: mvn surefire-report:report

      # Store code coverage report as artifacts
      - store_artifacts:
          path: target/site/jacoco/index.html
          destination: code-coverage

      # Store test results (JUnit XML)
      - store_test_results:
          path: target/surefire-reports
      
workflows:
  hello_and_goodbye:
    jobs:
      - say_hello
      - say_goodbye
      - build_and_test_maven
