version: 2.1

jobs:
  say_hello:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to YAML onkar!"
  
  say_goodbye:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say goodbye to YAML new !"
  
  
  build_and_test_maven:
    docker:
      - image: cimg/openjdk:17.0  
    steps:
      - checkout  

      - run: |
          mvn clean install
          export MAVEN_EXIT_CODE=$?

      - run: mvn jacoco:report

      - run: echo "Uploading code coverage results..."
      - store_artifacts:
          path: target/site/jacoco/index.html
          destination: code-coverage

workflows:
  hello_and_goodbye:
    # List of jobs that will run
    jobs:
      - say_hello
      - say_goodbye
      - build_and_test_maven
