name: slack_github_action

on:
  push:
    branches:
      - master

jobs:
  slack_notifier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Maven project
        run: |
          mvn clean install
          export MAVEN_EXIT_CODE=$?

      - name: Generate code coverage report
        run: |
          
          mvn jacoco:report

      - name: Publish code coverage result
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: target/site/jacoco/index.html

      - name: Send notification on Slack using Webhooks - Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Git push done in the repo. Maven project built successfully. Code coverage report published."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send notification on Slack using Webhooks - Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Git push done in the repo. Maven build failed. Please check the build logs for details."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
