name: slack_github_action

on:
  push:
    branches:
      - self_hosted_runner_windows

jobs:
  slack_notifier:
    runs-on: self_hosted_label

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set PowerShell Execution Policy
        run: |
             Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Maven project
        run: |
          # cd  D:\apache-maven-3.6.3\bin\
          mvn clean install
          $env:MAVEN_EXIT_CODE=$LASTEXITCODE
      - name: Generate code coverage report
        run: |
          
          mvn jacoco:report
      - name: Publish code coverage result
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: target/site/jacoco/index.html
      - name: Download SonarScanner for MSBuild
        uses: SonarSource/sonar-scanner-msbuild@master
        with:
          sonarLogin: ${{ secrets.SONAR_TOKEN }}
          organization: 'sonarqube-gitaction'
          projectKey: 'sonarqube-gitaction_gitaction-poc-10-java-ci'

      - name: SonarQube Scan
        run: MSBuild.SonarQube.Runner.exe begin /k:"sonarqube-gitaction_gitaction-poc-10-java-ci" /d:sonar.organization="sonarqube-gitaction" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.java.binaries="target/classes" /d:sonar.sources="."

      # - name: Build Maven project (again if needed)
      #   run: |
      #     mvn clean install
      #     $env:MAVEN_EXIT_CODE=$LASTEXITCODE

      - name: SonarQube Scan (end)
        run: MSBuild.SonarQube.Runner.exe end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Send notification on Slack using Webhooks - Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Maven project built successfully."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send notification on Slack using Webhooks - Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Maven build failed. Please check the build logs for details."
            }
        env:
          # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
