name: slack_github_action

on:
  push:
    branches:
      - main

jobs:
  slack_notifier:
    runs-on: self_hosted_label

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set PowerShell Execution Policy
        run: .\Set-ExecutionPolicy.ps1

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Maven project
        run: |
          mvn clean install
          export MAVEN_EXIT_CODE=$?
      - name: Generate code coverage report
        run: |
          
          mvn jacoco:report
      - name: Publish code coverage result
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: target/site/jacoco/index.html
      - name: Download SonarScanner for MSBuild
        uses: SonarSource/sonar-scanner-msbuild@4.10.0
        with:
          sonarLogin: ${{ secrets.SONAR_TOKEN }}
          organization: 'sonarqube-gitaction'
          projectKey: 'sonarqube-gitaction_gitaction-poc-10-java-ci'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Send notification on Slack using Webhooks - Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Maven project built successfully."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send notification on Slack using Webhooks - Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Maven build failed. Please check the build logs for details."
            }
        env:
          # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
