name: slack_github_action

on:
  push:
    branches:
      - self_hosted_runner_windows

jobs:
  slack_notifier:
    runs-on: self_hosted_label

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set PowerShell Execution Policy
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Maven project
        run: |
          mvn clean install
          $env:MAVEN_EXIT_CODE=$LASTEXITCODE

      - name: Generate code coverage report
        run: |
          mvn jacoco:report

      - name: Publish code coverage result
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: target/site/jacoco/index.html

      - name: SonarQube Scan
        run: |
          # Path to SonarScanner executable (adjust based on your installation)
          $sonarScannerPath = "D:\sonarqube-7.9.1\bin\windows-x86-64\sonar-scanner.bat"
          
          # Run SonarScanner with necessary parameters
          & $sonarScannerPath -Dsonar.organization=sonarqube-gitaction `
                              -Dsonar.projectKey=sonarqube-gitaction_gitaction-poc-10-java-ci `
                              -Dsonar.sources=. `
                              -Dsonar.host.url=https://sonarcloud.io `
                              -Dsonar.java.binaries=./target/classes `
                              -Dsonar.login=$env:SONAR_TOKEN

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Send notification on Slack using Webhooks - Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Maven project built successfully."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send notification on Slack using Webhooks - Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Maven build failed. Please check the build logs for details."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
